window.PK_CONFIG = {
  API_URL: 'https://script.google.com/macros/s/AKfycbz7mAd3lHIVkJedI1TjNpmfB758odY1V79JUXH2B7udiw7HQNXjFiU0HvAkMIePDs-IRw/exec',
  APP_NAME: 'SISTEM DIGITAL PENJAMINAN KUALITI SK SG ABONG',
  SCHOOL_NAME: 'SKSA'
};
