window.PK_CONFIG = {
  NEON_DATABASE_URL: 'https://ep-cold-lake-b4yhxpjs.c-6.us-east-2.aws.neon.tech/neondb',
  APP_NAME: 'SISTEM DIGITAL PENJAMINAN KUALITI SK SG ABONG',
  SCHOOL_NAME: 'SKSA',
  SCHOOL_OFFICIAL_NAME: 'SEKOLAH KEBANGSAAN SUNGAI ABONG',
  SCHOOL_CODE: 'JBA5095',
  BACKEND: 'NEON'
};
